server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      pool-name: user-service-data-pool
      minimum-idle: 10
      idle-timeout: 600000
      maximum-pool-size: 20
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: localhost
      database: 2
      port: 6379
      password:
      timeout: 3s
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数
          max-idle: 8 #连接池最大空闲连接数
          min-idle: 0 #连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

---
security:
  demo:
    jwtSecretKey: 'yourSecretKey'


